### ISSUE TITLE
Make an opt-in way to use system ICDs

### ISSUE THREAD

**Issue by isuruf** [conda-forge/ocl-icd-feedstock#11]
This can be done by a post-link script. These scripts are run once per version when conda installs the package for the first time.

**Comment by inducer** [comment]
I mean, technically we should hack ocl-icd to look in both places, but sure, this would do as a start.

**Comment by inducer** [comment]
Given how terrible many ICDs are, I am reconsidering how good of an idea this was.

Here's an example crash caused by this: https://gitlab.tiker.net/inducer/pytential/-/jobs/70840

**Comment by inducer** [comment]
This also makes it pretty difficult to force CI runs onto the Conda-installed ICD (e.g. if pocl is also installed system-wide).

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/ci-support/commit/8024a5faa50bff5991e27c283961581f70b7b9bf

**Comment by inducer** [comment]
While, ideologically speaking, this should be the default, from the perspective of shipping reliable software, this needs to be opt-in. I'll submit an MR to back out #12, and we can debate how to best reimplement this in an opt-in fashion.

**Comment by inducer** [comment]
#13 backs out #12.

**Comment by isuruf** [comment]
I think this should be default and we can give a way to opt-out of it. For example, `conda install ocl-icd` symlinks system icds and `conda install ocl-icd no-system-icds` doesn't.

**Comment by inducer** [comment]
I completely disagree. Let's discuss at our meeting today.

**Comment by inducer** [comment]
#14 addresses this. Thanks, @isuruf!

**Comment by jakirkham** [comment]
Now there is an opt-in option with [`ocl-icd-system`]( https://github.com/conda-forge/ocl-icd-system-feedstock ).
