### ISSUE TITLE
C++ OpenCL header

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/ocl-icd-feedstock#25]
### Comment:

I have an OpenCL package that needs the OpenCL C++ header(s) from https://github.com/KhronosGroup/OpenCL-CLHPP.  There's really only one and a legacy deprecated name header that warns and includes the one.

I asked upstream ocl-icd if they wanted to start including the C++ headers in their install in https://github.com/OCL-dev/ocl-icd/issues/22

@conda-forge/ocl-icd, I'm thinking it might make the most sense to create a new `khronos-opencl-clhpp` package that depends on `ocl-icd` and provides the C++ header.  Do you agree or should we add the C++ header directly into our `ocl-icd` package?

**Comment by isuruf** [comment]
They are in `clhpp` conda package

**Comment by timsnyder-siv** [comment]
Thanks @isuruf!
