### ISSUE TITLE
Noisy warning on environment activation when ffmpeg or libopencv are installed in an environment on Linux

### ISSUE THREAD

**Issue by traversaro** [conda-forge/ocl-icd-feedstock#29]
### Comment:

Since https://github.com/conda-forge/openvino-feedstock/pull/73 has been merged, all the new environments in which I install `opencv` or `ffmpeg` get a big and scary warning:

~~~
WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or
- Make your system-wide implementation visible by installing ocl-icd-system conda package.
~~~

This warning actually comes from the `ocl-icd` package, that comes from the `libopencv --> libopenvino-intel-gpu-plugin --> ocl-icd` dependency chain. The warning is printed on every environment activation, and kind of confuses users, especially the one that do not care or even do not know anything about OpenCL. I do not have any specific opinion on OpenCL so removing `ocl-icd-system` may be perfectly fine for me, but do you think we could avoid this extremely noisy warning? 

fyi @conda-forge/ffmpeg @conda-forge/opencv @conda-forge/openvino @conda-forge/ocl-icd

**Comment by matthiasdiener** [comment]
I'd be supportive of removing the warning (in https://github.com/conda-forge/ocl-icd-feedstock/blob/main/recipe/activate.sh).

**Comment by iamanigeeit** [comment]
Worse still: the double square brackets [[ ]] syntax is specific to bash and running on `sh` will make activation fail.

**Comment by traversaro** [comment]
fyi @xela-95

**Comment by vvzen** [comment]
I'd second removing the warning, or at least logging to stderr, as common practice in UNIX.

https://github.com/conda-forge/ocl-icd-feedstock/blob/dfffb6a760331082d63878159409321e3deee841/recipe/activate.sh#L3

The fact that the logging happens on stdout will break all CLIs that activate an environment and run things programmatically, for example a `python3 -m pip list --json` .

e.g.:
```bash
bash -lc 'conda activate /path/to/my/env && python3 -m pip list --format json' | jq
```

gets forced to become:
```bash
bash -lc 'conda activate /path/to/my/env 1>/dev/null && python3 -m pip list --format json' | jq
```

**Comment by xela-95** [comment]
fyi @flferretti

**Comment by hmaarrfk** [comment]
🎆  sorry for the accidental click

**Comment by traversaro** [comment]
Thanks a lot @matthiasdiener !
