### ISSUE TITLE
Ship CMake metadata

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/ocl-icd-feedstock#33]
We [have](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Focl-icd-2.3.2-hd590300_1.conda) all the headers that are necessary, but `find_package(OpenCL)` runs into:
```
-- Checking for module 'OpenCL'
--   Package 'OpenCL-Headers', required by 'OpenCL', not found
CMake Error at $BUILD_PREFIX/share/cmake-3.30/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - OpenCL
```

**Comment by h-vetinari** [comment]
Would be nice to switch to CMake builds here... The lack of CMake metadata is a pain. 😑

**Comment by isuruf** [comment]
Will be fixed with https://github.com/conda-forge/staged-recipes/pull/28410 and then a PR here.

**Comment by isuruf** [comment]
Fixed now
