### ISSUE TITLE
Add a README to ocl-icd vendor directory

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ocl-icd-feedstock#5]
Based on this [discussion]( https://github.com/conda-forge/ocl-icd-feedstock/pull/4#discussion_r124898937 ) am raising this issue to add a README to `ocl-icd`'s vendor directory. This README would probably explain what the directory is for and maybe note that users should symlink `*.icd` files from their system ocl-icd vendor directory into the conda environment one if they wish to use them.

**Comment by tiagoantao** [comment]
I have raised this (wrongly) on https://github.com/conda-forge/pyopencl-feedstock/issues/22
Here is a modified version

The build recipe of ocl-ocd points to an ICD directory list on
$PREFIX/etc/OpenCL/vendors

But nothing populates that directory, as far as I know. I think that either:

1. It could point to /etc/OpenCL/vendors , though that would create a dependency on the OS

2. Users should be informed that they need to take action (e..g copy ICDs from /etc/OpenCL/vendors). I.e. some documentation should be provided elsewhere

3. There needs to be conda packages of ICDs

At this stage, the current implementation is, I believe technically broken in the sense that the user will have an error if trying to use this and there is neither ICD implementations available as conda packages or the ability to link the system ICDs

**Comment by inducer** [comment]
> But nothing populates that directory, as far as I know. 

`conda install pocl` will populate that directory. (with one file)

> There needs to be conda packages of ICDs

https://github.com/inducer/pocl-feedstock is one ICD. I'd love to have more.

> Users should be informed that they need to take action (e..g copy ICDs from /etc/OpenCL/vendors). I.e. some documentation should be provided elsewhere

I agree, and I'm open to suggestions on how to do that. Can conda show text during install?

**Comment by isuruf** [comment]
There is a message now
